# 使用的语言
lang: Chinese
# debug模式
debug: true
# 拓展语义包含
extended-syntax:
  system: true
  redis: true
  paper: true
# 魔语快捷执行
coding: true

# ProtocolLib支持
ProtocolLib:
  item-variable-refresh: true
  item-papi-refresh: true


constants:
  plugin-name: "MagicPaper"

cool-down:
  bore-add:
    time: 1000
    message: "&c你的操作过于频繁，请稍后再试"

bore-listener: true

default-file: true